config/routes.rb
Rails.application.routes.draw do
  post 'reservation/:room_id/create', to:'reservation#create' #予約実行

  get 'users/new', to:'users#new' #アカウント新規登録フォーム表示
  get 'users/login', to:'users#login_form' #ログインフォーム表示
  post 'users/login', to:'users#login' #ログイン
  get 'users/logout', to:'users#logout' #ログアウト
  post 'users/create', to:'users#create' #アカウント新規登録
  get 'users/:id/account', to:'users#account' #アカウント詳細
  get 'users/:id/edit', to:'users#edit' #アカウント編集
  post 'users/update', to:'users#update' #アカウント更新
  get 'users/:id/reservations', to:'users#reservations' #予約済みルーム一覧
  get 'users/:id', to:'users#show' #登録済みルーム一覧
  
  get 'rooms/new', to:'rooms#new' #ルーム新規登録フォーム表示
  post 'rooms/create', to:'rooms#create' #ルーム新規登録
  get 'rooms/search_area', to:'rooms#search_area' #「場所で検索」結果
  get 'rooms/search_keyword', to:'rooms#search_keyword' #「キーワードで検索」結果
  get 'rooms/:id', to:'rooms#show' #ルーム詳細

  get '/', to:'home#top' #トップページ
  get 'home/top', to:'home#top' #トップページ
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  validates :user_id, {presence: true}
  validates :room_id, {presence: true}
end

app/models/room.rb
class Room < ApplicationRecord
  validates :user_id, {presence: true}

  def self.search_area(search)
    if search
      Room.where(['address LIKE ?', "%#{search}%"])
    else
      Room.all
    end
  end

  def self.search_keyword(search)
    if search
      Room.where(['name LIKE ? OR address LIKE ? OR introduction LIKE ?', "%#{search}%", "%#{search}%", "%#{search}%"])
    else
      Room.all
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, {presence: true}
  validates :email, {presence: true}
  validates :password, {presence: true}

  def rooms
    return Room.where(user_id: self.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_current_user

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/reservation_controller.rb
class ReservationController < ApplicationController
  before_action :set_current_user
  
  def create
    @reservation = Reservation.new(
      user_id: @current_user.id,
      room_id: params[:room_id],
      start: params[:start],
      end: params[:end],
      people: params[:people]
    )
    @reservation.save
    flash[:notion] = "予約が完了しました"
    redirect_to("/")
  end

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
  end

  def create
    @room = Room.new(
      name: params[:name],
      introduction: params[:introduction],
      price: params[:price],
      address: params[:address],
      user_id: @current_user.id
    )

    if params[:image]
      @room.image_name = "#{@room.name}.jpg"
      image = params[:image]
      File.binwrite("public/room_image/#{@room.image_name}", image.read)
    else
      @room.image_name = "default_room.png"
    end

    if @room.save
      flash[:notice] = "新規登録しました"
      redirect_to("/users/#{@current_user.id}")
    else
      render("rooms/new")
    end
  end

  def search_area
    @rooms = Room.search_area(params[:search])
  end

  def search_keyword
    @rooms = Room.search_keyword(params[:search])
  end
    
  def show
    @room = Room.find_by(id: params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_current_user

  def index
    @users = User.all
  end

  def account
    @user = User.find_by(id: session[:user_id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(
      name: params[:name],
      email: params[:email],
      password: params[:password],
      image_name: "default_user.png"
    )
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "新規登録しました"
      redirect_to("/")
    else
      render("users/new")
    end
  end

  def edit
    @user = User.find_by(id: session[:user_id])
  end

  def update
    @user = User.find_by(id: session[:user_id])
    @user.name = params[:name]
    @user.email = params[:email]
    @user.password = params[:password]
    @user.introduction = params[:introduction]
    if params[:image]
      @user.image_name = "#{@user.id}.jpg"
      image = params[:image]
      File.binwrite("public/user_image/#{@user.image_name}", image.read)
    end

    if @user.save
      flash[:notice] = "ユーザー情報を更新しました"
      redirect_to("/users/account")
    else
      render("users/edit")
    end

  end

  def login_form
  end

  def login
    @user = User.find_by(
      name: params[:name],
      password: params[:password]
    )

    if @user
      session[:user_id] = @user.id
      flash[:notice] = "ログインしました"
      redirect_to("/")
    else
      render("users/login_form")
    end

  end

  def logout
    session[:user_id] = nil
    flash[:notice] = "ログアウトしました"
    redirect_to("/")
  end

  def rooms
    return Room.where(user_id)
  end

  def show
    @user = User.find_by(id: params[:id])
  end

  def reservations
    @user = User.find_by(id: params[:id])
    @reservations = Reservation.where(user_id: @user.id)
    
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/top.html.erb
<div class="top">
  
  <div class="padding"></div>

  <div class="top-box">
    <h2>
    Potepan Shareでまだ体験したことのない旅をしよう
    </h2>
    <%= form_tag(rooms_search_area_path,:method => 'get') do %>
      <%= label_tag '地域で検索' %>
      <%= text_field_tag :search %>
      <%= submit_tag 'Search', :address => nil %>
    <% end %>

    <%= form_tag(rooms_search_keyword_path,:method => 'get') do %>
      <%= label_tag 'キーワードで検索' %>
      <%= text_field_tag :search %>
      <%= submit_tag 'Search', :address => nil %>
    <% end %>
  </div>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLesson2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <header>

      <div class="header-img">
        <a href="/"><img src="/logo.png"></a>
      </div>
      <div class="header-right">
        <ul class="header-list">
          <% if @current_user %>
            <li class="align">
              <%= @current_user.name %>
            </li>
            <li>
              <div class="currentuser-img">
              <img src="<%= "/user_image/#{@current_user.image_name}" %>">
              </div>
            </li>
            <li class="align line-bottom">
              <%= link_to("ルーム登録", "/rooms/new") %>
            </li>
            <li class="align line-bottom">
              <%= link_to("ルーム一覧", "/users/#{@current_user.id}") %>
            </li>
            <li class="align line-bottom">
              <%= link_to("予約済み一覧", "/users/#{@current_user.id}/reservations") %>
            </li>
            <li class="align line-bottom">
              <%= link_to("アカウント", "/users/#{@current_user.id}/account") %>
            </li>
            <li class="align line-bottom">
              <%= link_to("ログアウト", "/users/logout") %>
            </li>
          <% else %>
            <li class="login-btn">
              <a href="/users/login">ログイン</a>
            </li>
            <li class="regi-btn">
              <a href="/users/new">新規登録</a>
            </li>
          <% end %>
        </ul>
      </div>
      
    </header>
    
    <div class="flash">
      <% if flash[:notice] %>
        <%= flash[:notice] %>
      <% end %>
    </div>

    <%= yield %>

    <footer>
      <p class="footer">
        @2021 FUJIKAWA-IKU.INC
      </p>
    </footer>

  </body>

</html>

app/views/rooms/index.html.erb
<h2 class="title">
  登録済みルーム一覧
</h2>

<table class="roomtable">

  <thead>
    <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>料金</th>
      <th>作成日</th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td class="roomindex-img">
          <div class="roomimg">
            <%= link_to image_tag("/room_image/#{room.image_name}"), "/rooms/#{room.id}" %>
          </div>
        </td>

        <td><%= room.name %></td>

        <td><%= room.user_id %></td>

        <td><%= room.introduction %></td>

        <td>¥<%= room.price %></td>

        <td><%= l room.created_at %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>

app/views/rooms/new.html.erb
<div class="room-box">

  <h2>
  ルーム登録
  </h2>

  <%= form_tag("/rooms/create", {multipart: true}) do %>
    <div class="roomnew">
      <label for="name">名前　</label><input name="name" placeholder="ルーム名を入力">
    </div>
    <div class="roomnew padding">
      <label for="introduction">ルーム紹介　</label><textarea name="introduction"></textarea>
    </div>
    <div class="roomnew">
      <label for="price">料金　</label><input name="price" placeholder="一日あたりの料金を入力" type="number">
    </div>
    <div class="roomnew">
      <label for="address">住所　</label><input name="address" placeholder="住所を入力">
    </div>
    <div class="roomnew">
      <label for="image">ルーム画像　</label><input name="image" type="file">
    </div>
    <div class="room-btn">
      <input class="room-btn" value="ルーム登録" type="submit">
    </div>
  <% end %>

</div>

app/views/rooms/search_area.html.erb
<h2 class="title">
  検索結果
</h2>

<div class="search-box">
  <% @rooms.each do |room| %>
    <div class="search-result">
      <div class="search-img">
        <%= link_to image_tag("/room_image/#{room.image_name}"), "/rooms/#{room.id}" %>
      </div>
      <div class="search-disc">
        <p class="roomname"><%= room.name %></p>
        <p class="roomaddress"><%= room.address %></p>
        <p class="roomprice">¥<%= room.price %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/search_keyword.html.erb
<h2 class="title">
  検索結果
</h2>

<div class="search-box">
  <% @rooms.each do |room| %>
    <div class="search-result">
      <div class="search-img">
        <%= link_to image_tag("/room_image/#{room.image_name}"), "/rooms/#{room.id}" %>
      </div>
      <div class="search-disc">
        <p class="roomname"><%= room.name %></p>
        <p class="roomaddress"><%= room.address %></p>
        <p class="roomprice">¥<%= room.price %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/rooms/show.html.erb
<div class="roomshow">

  <div class="roomshow-img">
    <img src="<%= "/room_image/#{@room.image_name}" %>">
  </div>
  <p class="roomname"><%= @room.name %></p>
  <p class="roomaddress"><i class="fas fa-map-marker-alt"></i> <%= @room.address %></p>
  <p class="roomintroduction"><%= @room.introduction %></p>
  <p class="roomprice">¥<%= @room.price %></p>
  
  <% if @current_user %>
    <% if Reservation.find_by(user_id: @current_user.id, room_id: @room.id) %>
      <p>予約済み</p>
    <% else %>
      <%= form_tag("/reservation/#{@room.id}/create", {method: "post"}) do %>
        <p>開始日</p>
        <input type="date" name="start">
        <p>終了日</p>
        <input type="date" name="end">
        <p>人数</p>
        <input type="number" name="people">
          <p><input value="予約" type="submit"></p>
      <% end %>
    <%end%>
  <% else %>
    <%= link_to("ログイン", "/users/login") %>
  <% end %>

</div>

app/views/users/account.html.erb
<div class="account-box">

  <div class="account-img">
    <img src="<%= "/user_image/#{@current_user.image_name}" %>">
  </div>
  <div class="intro-box">
    <div class="intro-list">
      <span>名前</span>
      <p><%= @current_user.name %></p>
    </div>
    <div class="intro-list">
      <span>メールアドレス</span>
      <p><%= @current_user.email %></p>
    </div>
    <div class="intro-list">
      <span>パスワード</span>
      <p><%= @current_user.password %></p>
    </div>
    <div class="intro-list">
      <span>自己紹介</span>
      <p><%= @current_user.introduction %></p>
    </div>
  </div>
  
</div>

<p class="center">
  <%= link_to("編集", "/users/#{@user.id}/edit") %>
</p>

app/views/users/edit.html.erb
<div class="edit-box">

  <h2>
  プロフィール
  </h2>

  <div class="edit-img">
    <img src="<%= "/user_image/#{@current_user.image_name}" %>">
  </div>
  
  <%= form_tag("/users/update", {multipart: true}) do %>
    <div class="editform">
      <label for="name">名前　</label><input class="border" name="name" placeholder="名前" value="<%= @current_user.name %>">
    </div>
    <div class="editform">
      <label for="email">メールアドレス　</label><input class="border" name="email" placeholder="メールアドレス" value="<%= @current_user.email %>">
    </div>
    <div class="editform">
      <label for="password">パスワード　</label><input class="border" name="password" placeholder="パスワード" type="password" value="<%= @current_user.password %>">
    </div>
    <div class="editform">
      <label for="image">アイコン　</label><input name="image" type="file">
    </div>
    <div class="editform padding">
      <label for="introduction">自己紹介　</label><textarea class="border" name="introduction"><%= @user.introduction %></textarea>
    </div>
    
    <div class="btn">
      <input value="更新" type="submit">
    </div>
  <% end %>

</div>

app/views/users/login_form.html.erb
<div class="form-box">

  <h2>
  ログイン
  </h2>
  
  <%= form_tag("/users/login") do %>
    <div class="form">
      <input name="name" placeholder="名前">
    </div>
    <div class="form">
      <input name="password" placeholder="パスワード" type="password">
    </div>
    <input name="login-btn" value="ログイン" type="submit">
  <% end %>
  
</div>

app/views/users/new.html.erb
<div class="form-box">

  <h2>
  ユーザー新規登録
  </h2>

  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li>
        <%= message %>
      </li>
    <% end %>
  </ul>
  
  <%= form_tag("/users/create") do %>
    <div class="form">
      <input name="name" placeholder="ユーザー名" value="<%= @user.name %>">
    </div>
    <div class="form">
      <input name="email" placeholder="メールアドレス" value="<%= @user.email %>">
    </div>
    <div class="form">
      <input name="password" placeholder="パスワード" type="password" value="<%= @user.password %>">
    </div>
    <input value="新規登録" type="submit">
  <% end %>
  
</div>

app/views/users/reservations.html.erb
<h2 class="title">
  予約済みルーム一覧
</h2>

<table class="roomtable">

  <thead>
    <tr>
    <th>ルーム画像</th>
    <th>ルーム名</th>
    <th>ルーム紹介</th>
    <th>合計料金</th>
    <th>開始日</th>
    <th>終了日</th>
    <th>予約確定日時</th>
    </tr>
  </thead>

  <tbody>
    <% @reservations.each do |reservation| %>
    <% room = Room.find_by(id: reservation.room_id) %>
      <tr>
        <td class="roomindex-img">
          <div class="roomimg">
            <%= link_to image_tag("/room_image/#{room.image_name}"), "/rooms/#{room.id}" %>
          </div>
        </td>

        <td><%= room.name %></td>

        <td><%= room.introduction %></td>

        <td>¥<%= reservation.people.to_i * room.price.to_i %></td>

        <td><%= reservation.start %></td>

        <td><%= reservation.end %></td>

        <td><%= l reservation.created_at %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>

app/views/users/show.html.erb
<h2 class="title">
  登録済みルーム一覧
</h2>

<table class="roomtable">

  <thead>
    <tr>
    <th>ルーム画像</th>
    <th>ルーム名</th>
    <th>ルーム紹介</th>
    <th>料金</th>
    <th>作成日</th>
    </tr>
  </thead>

  <tbody>
    <% @user.rooms.each do |room| %>
      <tr>
        <td class="roomindex-img">
        <div class="roomimg">
          <%= link_to image_tag("/room_image/#{room.image_name}"), "/rooms/#{room.id}" %>
        </div>
        
        </td>

        <td><%= room.name %></td>

        <td><%= room.introduction %></td>

        <td>¥<%= room.price %></td>

        <td><%= l room.created_at %></td>
      </tr>
    <% end %>
  </tbody>
  
</table>